### ISSUE TITLE
Syntax Error: Unexpected Token Export

### ISSUE THREAD

**Issue by nebhead** [pguso/js-plugin-circliful#168]
Not sure if this is the right place to ask for help, but I'm trying to integrate the latest circliful script into my Flask/Bootstrap themed project but it doesn't seem to be working out for me.  I suspect it's my issue, but maybe others are experiencing it too.  

I've moved the following into my directory structures:

from:
```
/dist/circliful.js
/dist/main.css
```
to:
```
/static/js/circliful.js
/static/css/main.jss
```

Here's my code invoking circliful once:
```
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css" />

		<!-- Circliful CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css" />

		<!-- Adding a Favicon -->
		<link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />

    <!-- WebApp Manifest -->
    <link rel="manifest" href="{{ url_for('manifest') }}">

    <title>App History</title>

  </head>
	<body>

		<!-- Navbar Header -->
		<nav class="navbar sticky-top navbar-dark bg-dark">

			<a class="navbar-brand" href="#">
				<img src="{{ url_for('static', filename='img/launcher-icon-1x.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
				<b>AppName</b></a>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="nav navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="#">Dashboard</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/recipes">Recipes</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link" href="/history">History <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/settings">Settings</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/admin">Admin</a>
						</li>
					</ul>
				</div>

		</nav>

		<br>

		<div class="container theme-showcase" role="main">
			<br>
				<div class="row">
					<div class="col">
						<div class="card">
							<div class="card-header bg-primary text-white"><h5><i class="fas fa-history"></i> History</h5></div>
			        <div class="card-body">
								<div id="MyCircle"></div>
			        </div> <!-- End of card body -->
			        <div class="card-footer bg-light">
			            <button type="button" class="btn btn-outline-primary">Button</button>
			        </div>
						</div> <!-- End of Card -->
					</div> <!-- End of Column -->
				</div> <!-- End of Row -->

		<br>
		<br>
		<br>
	<!-- JavaScript -->
	<!-- jQuery first, then Bootstrap JS -->
	<script src="{{ url_for('static', filename='js/jquery-3.4.1.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/circliful.js') }}"></script>
	<script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/all.js') }}"></script>
	<script>
		circliful.newCircle({
		    percent: 80,
		    id: 'MyCircle',
		    type: 'simple',
		    foregroundCircleWidth: 10,
		    startAngle: -180,
		    backgroundCircleWidth: 10,
		    text: '100°F',
		    textReplacesPercentage: true,
				strokeLinecap: "round",
		});
	</script>

</body>
</html>
```

Chrome reports: Uncaught SyntaxError: Unexpected token 'export' in the developer console.  

When I dig into that error, I see at the very end of the file: 
```
]);
export default circliful;
export {circliful};
```

Chrome is highlighting 'export default circliful;' as the error.  

I am sure I'm not doing something right, help would be appreciated!  

Thanks, 
Ben.

**Comment by nebhead** [comment]
FYI, I removed the last two export lines from the .js and it seems to be working now.

**Comment by pguso** [comment]
sorry for the inconvenience, removed the export lines.

**Comment by nebhead** [comment]
Thank you!

Now I have weird behavior with another page where I have a section of the page refreshing... causing the whitespace to be added on each refresh underneath the circle.  Still debugging.

**Comment by pguso** [comment]
I added your code here https://jsfiddle.net/jy3146ck/1/ what do you mean with "on each refresh"?

**Comment by nebhead** [comment]
Actually probably a totally different unrelated issue.  

On another page (my index.html page), I have three circles displayed that I want to periodically refresh.  The circles are defined in a separate data.html file, in <script> tags.  Then I have another script on my index page that will refresh the data every 10 seconds: 

```
<script>
		$(document).ready(function(){
			$('#refreshmedata').load("/data");
			setInterval(function(){
			  $('#refreshmedata').fadeOut('fast').load("/data").fadeIn('fast');
			}, 10000);
		});
</script>
```

On the first page load, it works great, displays all three of the circles.  However, when the data refreshes, it creates white space below each of the circles, approximately the same size as the circles.  This whitespace gets longer and longer with each refresh of the data.  


![Screenshot from 2020-06-03 13-28-51](https://user-images.githubusercontent.com/19876886/83685995-59e7ca00-a59e-11ea-8206-012c9815db89.png)
![Screenshot from 2020-06-03 13-29-28](https://user-images.githubusercontent.com/19876886/83686005-5c4a2400-a59e-11ea-95e8-7ace179e356b.png)

**Comment by pguso** [comment]
Are you using the actual version, i fixed something like that in an older version? I tried to reproduce your problem https://jsfiddle.net/64ag2r3p/1/ but i couldnt, maybe you can change the fiddle so it reproduces you behavior?

**Comment by nebhead** [comment]
Thanks for your help!  I'm actually building a little web-app for a RaspberryPi to power my pellet grill.  The dash will incorporate data on temperature of the grill, and a couple of food probes.  

The way it works right now, is that I have the circle scripts in a file called data.html.  Normally the values in the file would be populated dynamically by my Flask script.  When you go to the dashboard (index.html), it will reference the javascript I mentioned above, to reload the data.html file every 10 seconds.  This should refresh the data in the circles - which does work with Chart.js - but I simply didn't like chart.js as much as I like Circliful.  

I tried to put this into a the jsfiddle below, but I'm not sure how to have a seperate data.html file get called (I'm a bit of a noob to JS).  

https://jsfiddle.net/6vrmnejx/3/

The first part of the JS is the code that I use in my index.html (dashboard) to reload the data.html data from my flask app.  

The second part is what would be in my data.html

Thanks!
Ben.

**Comment by nebhead** [comment]
Just for clarity, here are the files, basically laid out (with much of the header, etc. stripped out for simplicity). 

**index.html** (depends on circliful, bootstrap, jquery, fontawesome)
```
		<!-- Navbar Header -->
		<nav class="navbar sticky-top navbar-dark bg-dark">

			<a class="navbar-brand" href="#">
				<b>Web App</b></a>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="nav navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/recipes">Recipes</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/history">History</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/settings">Settings</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/admin">Admin</a>
						</li>
					</ul>
				</div>

		</nav>

		<br>

		<div class="container theme-showcase" role="main">

			<!-- Data Section -->
			<div id="refreshmedata"></div>

			<div class="row">

				<div class="col">
					<div class="card">
				  	<div class="card-body text-center">
							<div id="GrillTempCircle"></div>
						</div> <!-- End of card body -->
						<div class="card-footer text-center">
							<a href="/settings" class="btn btn-success btn-sm float-right" role="button"><i class="fas fa-cog"></i></a>
							<h5><i class="fas fa-temperature-high"></i> Grill</h5>
						</div>
					</div> <!-- End of card -->
				</div> <!-- End of Column -->

				<div class="col">
					<div class="card">
						<div class="card-body text-center">
							<div id="Probe1TempCircle"></div>
						</div> <!-- End of card body -->
						<div class="card-footer text-center">
							<a href="/settings" class="btn btn-success btn-sm float-right" role="button"><i class="fas fa-cog"></i></a>
							<h5><i class="fas fa-temperature-high"></i> Probe 1</h5>
						</div>
					</div> <!-- End of card -->
				</div> <!-- End of Column -->

				<div class="col">
					<div class="card">
						<div class="card-body text-center">
							<div id="Probe2TempCircle"></div>
						</div> <!-- End of card body -->
						<div class="card-footer text-center">
							<a href="/settings" class="btn btn-success btn-sm float-right" role="button"><i class="fas fa-cog"></i></a>
							<h5><i class="fas fa-temperature-high"></i> Probe 2</h5>
						</div>
					</div> <!-- End of card -->
				</div> <!-- End of Column -->

			</div> <!-- End of Row -->

			<br>
			<br>

			<!-- Event History Section -->
			<div class="row">
				<div class="col">
					<div class="card">

						<div class="card-header bg-primary text-white"><h5><i class="fas fa-history"></i> Event History (last 10 items)</h5></div>

		        <div class="card-body">
							History will go here.
		        </div>

		        <div class="card-footer bg-light">
		          <form name="input" action="/history">
		            <button type="submit" class="btn btn-outline-primary">Full Event Logs</button>
		          </form>
		        </div>

		      </div> <!-- End of Card -->
				</div> <!-- End of Col -->
			</div> <!-- End of Row -->

		</div> <!-- End main showcase -->

<script>
		$(document).ready(function(){
			$('#refreshmedata').load("/data");
			setInterval(function(){
				$('#refreshmedata').fadeOut('fast').load("/data").fadeIn('fast');
			}, 10000);
		});
</script>
```

**data.html**
```
<script>
circliful.newCircle({
	    percent: 45,
	    id: 'GrillTempCircle',
	    type: 'simple',
	    foregroundCircleWidth: 10,
	    startAngle: -180,
	    backgroundCircleWidth: 10,
	    text: '180°F',
	    textReplacesPercentage: true,
			strokeLinecap: "round",
	});

	circliful.newCircle({
	    percent: 40,
	    id: 'Probe1TempCircle',
	    type: 'simple',
	    foregroundCircleWidth: 10,
	    startAngle: -180,
	    backgroundCircleWidth: 10,
	    text: '120°F',
	    textReplacesPercentage: true,
			strokeLinecap: "round",
	});

	circliful.newCircle({
	    percent: 38,
	    id: 'Probe2TempCircle',
	    type: 'simple',
	    foregroundCircleWidth: 10,
	    startAngle: -180,
	    backgroundCircleWidth: 10,
	    text: '118°F',
	    textReplacesPercentage: true,
			strokeLinecap: "round",
	});
</script>

**Comment by pguso** [comment]
sorry for the late response. that sounds very interesting! If you still have this issue could you please add it to https://stackblitz.com or https://codesandbox.io/ there you can work with multiple files and share it with others.

**Comment by nebhead** [comment]
Thanks!  I really appreciate the help.  Circliful is great software and I definitely want to use it.  I still have the issue, so let me go try to use one of the sites you mentioned and see if I can reproduce there.  I'll let you know once I've got something going.

**Comment by nebhead** [comment]
@pguso OK, I think I got it reproducing here:  [https://codesandbox.io/s/festive-johnson-1xmbe?file=/index.html](https://codesandbox.io/s/festive-johnson-1xmbe?file=/index.html)

Let me know if you can see this or not.

**Comment by nebhead** [comment]
One other minor question around aesthetics, is if the text could be more centered vertically?

**Comment by pguso** [comment]
I see the problem, as you load the script again and again, it tries to add the svg container for the circle again, as the svg container already exists the circle doesnt get drawn again and it adds just an empty container. Why you do it this way? If you want to update several values of the circle you can do it like this.

save an instance of the circle into a variable
```
var grillTempCircle = circliful.newCircle({
    percent: 45,
    id: "GrillTempCircle",
    type: "simple",
    foregroundCircleWidth: 10,
    startAngle: -180,
    backgroundCircleWidth: 10,
    text: "180°F",
    textReplacesPercentage: true,
    strokeLinecap: "round"
  });
```

update values of that circle over the api
```
grillTempCircle.update([
      { type: "percent", value: 40 },
      { type: "text", value: "180°F" }
]);
```

I also added an example into your codesanbox.

I saw there is still an error in the library if the start angle is negative and the percentage is under 0 or over 100 the circle dont get drawn correctly - i will fix this on the weekend.

**Comment by nebhead** [comment]
Thank you so much!  I have to admit I'm very much a beginner when it comes to javascript and css, but I'm learning tons by just diving in - and your help means a lot to me.  

Your suggestion makes sense to me, and should hopefully be much cleaner than my current implementation.  I didn't realize you could just update the variables like this and have the data change.  This is wonderful.  

BTW - How do I view your example on codesandbox?

**Comment by nebhead** [comment]
Not to pile on, but not sure if you noticed, but the circle is shifted left inside the bootstrap "card" on my example.  It seems to be an issue with the placement of the SVG, but I can't quite figure it out.  If you happen to know how to center it horizontally, that would be wonderful.

**Comment by pguso** [comment]
I forgot to save my changes, here are they https://codesandbox.io/s/compassionate-pine-l8j7s :)

**Comment by nebhead** [comment]
Thank you so much!  I think this helps resolve my issues.  I still need to figure out how to center the circle inside the bootstrap card, but now I can carry on with the project!  Feel free to close this one.  Maybe I'll update you in the future when my project is ready to share on GitHub.

**Comment by pguso** [comment]
I opened an issue to check why the circle is not always in the center. It would be really nice to share your progress with me in the future. And if you not allready know them i can recommend this hands on tutorial for free to learn more about JavaScript https://www.codecademy.com/learn/introduction-to-javascript they have some other web courses for free

**Comment by nebhead** [comment]
Thank you so much!  I'll definitely check out that online course.  And I'll keep an eye on the other issue.
